on: push
name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/cargo@v1
        name: Run clippy
        with:
          command: clippy
      - uses: actions-rs/cargo@v1
        name: Build
        with:
          toolchain: stable
          command: build
          args: --release